langbridge/models.py
from flask_bcrypt import generate_password_hash, check_password_hash

from langbridge import db
from datetime import datetime


class User(db.Model):
    __tablename__ = "user"
    user_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    user_type = db.Column(db.String(10), nullable=False)

    __mapper_args__ = {
        "polymorphic_identity": "user",
        "polymorphic_on": user_type
    }

    def __repr__(self):
        return "User email %s" % self.email

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Teacher(User):
    __tablename__ = 'teacher'
    teacher_id = db.Column(None, db.ForeignKey('user.user_id'), primary_key=True)
    rating = db.Column(db.Integer, nullable=False)
    reviews = db.Column(db.String)

    __mapper_args__ = {"polymorphic_identity": "learner"}

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


class BankAccount(db.Model):
    __tablename__ = 'bank_account'
    user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'), primary_key=True)
    payment_type = db.Column(db.String(250), nullable=False)
    payment_details = db.Column(db.String(250), nullable=False)


    def __repr__(self):
        return f"Forecast('{self.forecast}', '{self.comment}')"


class Wallet(db.Model):
    __tablename__ = 'wallet'
    wallet_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'))
    balance = db.Column(db.Integer)


class Lesson(db.Model):
    __tablename__ = 'lesson'
    lesson_id = db.Column(db.Integer, primary_key=True)
    learner_id = db.Column(db.Integer, db.ForeignKey('user.user_id'))
    teacher_id = db.Column(db.Integer, db.ForeignKey('teacher.teacher_id'))
    aim = db.Column(db.String)
    format = db.Column(db.String)
    time = db.Column(db.String)


class LessonReview(db.Model):
    __tablename__ = 'lesson_review'
    review_id = db.Column(db.Integer, primary_key=True)
    learner_id = db.Column(db.Integer, db.ForeignKey('user.user_id'))
    rating = db.Column(db.Integer)
    comment = db.Column(db.String)
    reviewed_on = db.Column(db.String)


class Language(db.Model):
    __tablename__ = 'language'
    lang_id = db.Column(db.Integer, primary_key=True)
    language = db.Column(db.String)


class LanguageUser(db.Model):
    __tablename__ = 'language_user'
    lang_id = db.Column(db.Integer, db.ForeignKey('language.lang_id'), primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.user_id'), primary_key=True)

langbridge/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class SignUpForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(max=50)])
    email = StringField('Email Address',
                        validators=[DataRequired(), Length(max=50), Email()])
    submit = SubmitField('Sign Up')

langbridge/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import DevConfig

db = SQLAlchemy()


def create_app(config_class=DevConfig):

    app = Flask(__name__)

    app.config.from_object(config_class)

    db.init_app(app)

    from langbridge.models import Teacher, User, LanguageUser, Lesson, Language, LessonReview, Wallet
    with app.app_context():
        db.create_all()

    from langbridge.main.routes import bp_main
    app.register_blueprint(bp_main)

    return app

langbridge/main/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from langbridge import db
from langbridge.main.forms import SignUpForm
from langbridge.models import User

bp_main = Blueprint('main', __name__)


@bp_main.route("/")
@bp_main.route("/index", methods=['POST', 'GET'])
def home():
    return render_template('index.html', title='Index')


@bp_main.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('home'))
    return render_template('signup.html', title='Sign Up', form=form)

langbridge/templates/index.html
{% extends "layout.html" %}{% block content %}

<div class="column middle">
    <h2>Main Content Heading</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet pretium urna. Vivamus venenatis velit nec neque ultricies, eget elementum magna tristique. Quisque vehicula, risus eget aliquam placerat, purus leo tincidunt eros, eget luctus
        quam orci in velit. Praesent scelerisque tortor sed accumsan convallis.</p>
</div>


<form method="POST" action="">
    <input type="text" name="search" placeholder="Search...">
</form>
{% endblock content %}

langbridge/templates/layout.html
{# Base / layout HTML Parent page #}

<html>


<head>
    <title>{{ title }}</title>

    <link href="index.css" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

    <div class="header">
        <h1>Rain Blog</h1>
    </div>

    <div class="topnav">
        <a href="#" class="image"><img src="https://i.imgur.com/E0eL0wa.png"></a>
        <a href="{{ url_for('main.home') }}" class="active">Home</a>
        <a href="{{ url_for('main.signup') }}">Signup</a>
    </div>

    {% block content %}{% endblock content %}

</html>

langbridge/templates/post.html
{% extends "layout.html" %} {% block content %} {% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.user_id.username }}</a>
            <small class="text-muted">{{ post.datetime.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2>{{ post.forecast }}</h2>
        <p class="article-content">{{ post.comment }}</p>
    </div>
</article>
{% endfor %} {% endblock content %}

langbridge/templates/signup.html
{% extends "layout.html" %} {% block content %}
<div class="column middle">
    <h2>Main Content Heading</h2>

</div>

<form method="POST" action="">
    {{ form.hidden_tag() }}
    <label for="lname">Username</label> {{ form.username(class="form-control form-control-lg") }}
    <label for="lname">Email address</label>{{ form.email(class="form-control form-control-lg") }} {{ form.submit(class="btn btn-outline-info") }}
</form>
{% endblock content %}