comp0034_flask_login_complete/app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class User(UserMixin, db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    email = db.Column(db.Text, unique=True)
    password = db.Column(db.Text)
    user_type = db.Column(db.String(10), nullable=False)

    __mapper_args__ = {
        "polymorphic_identity": "user",
        "polymorphic_on": user_type
    }

    def __repr__(self):
        return "User email %s" % self.email

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Student(User):
    __tablename__ = 'student'
    id = db.Column(None, db.ForeignKey('user.id'), primary_key=True)
    student_ref = db.Column(db.Integer)
    grades = db.relationship('Grade', backref='students')

    __mapper_args__ = {"polymorphic_identity": "student"}

    def __repr__(self):
        return '<Student ID: {}, name: {}>'.format(self.student_ref, self.name)


class Teacher(User):
    __tablename__ = 'teacher'
    id = db.Column(None, db.ForeignKey('user.id'), primary_key=True)
    teacher_ref = db.Column(db.Text, nullable=False)
    title = db.Column(db.Text)
    courses = db.relationship('Course', backref='teachers')

    __mapper_args__ = {"polymorphic_identity": "teacher"}

    def __repr__(self):
        return '<Teacher {} {}>'.format(self.teacher_ref, self.title, self.name)


class Course(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    course_code = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text, nullable=False)
    teacher_id = db.Column(db.Integer, db.ForeignKey(Teacher.id), nullable=False)
    grades = db.relationship('Grade', backref='courses')

    def __repr__(self):
        return '<Course {}>'.format(self.code, self.name)


class Grade(db.Model):
    student_id = db.Column(db.Integer, db.ForeignKey(Student.id), nullable=False, primary_key=True)
    course_id = db.Column(db.Integer, db.ForeignKey(Course.id), nullable=False, primary_key=True)
    grade = db.Column(db.Text)

    def __repr__(self):
        return '<Grade {}>'.format(self.grade)

comp0034_flask_login_complete/app/main/forms.py
#forms.py for main



comp0034_flask_login_complete/app/__init__.py
from flask import Flask, render_template
from flask_login import LoginManager
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

from config import DevConfig

db = SQLAlchemy()
login_manager = LoginManager()
sess = Session()


def page_not_found(e):
    return render_template('404.html'), 404


def internal_server_error(e):
    return render_template('500.html'), 500


def create_app(config_class=DevConfig):
    """
    Creates an application instance to run
    :return: A Flask object
    """
    app = Flask(__name__)

    # Configure app wth the settings from config.py
    app.config.from_object(config_class)

    # Initialise plugins
    db.init_app(app)
    login_manager.init_app(app)

    from populate_db import populate_db
    from app.models import Teacher, Student, Course, Grade
    with app.app_context():
        db.create_all()
        populate_db()

    # Register error handlers
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    # Register Blueprints
    from app.main.routes import bp_main
    app.register_blueprint(bp_main)

    from app.auth.routes import bp_auth
    app.register_blueprint(bp_auth)

    return app

comp0034_flask_login_complete/app/main/__init__.py
#__init__.py for main

comp0034_flask_login_complete/app/main/routes.py
from datetime import datetime

from flask import render_template, Blueprint, request, flash, redirect, url_for, make_response
from sqlalchemy import or_
from sqlalchemy.orm import with_polymorphic

from app import db
from app.models import Course, Student, Teacher, User

bp_main = Blueprint('main', __name__)


@bp_main.route('/')
def index(name=""):
    if 'name' in request.cookies:
        name = request.cookies.get('name')
    return render_template('index.html', name=name)


@bp_main.route('/courses', methods=['GET'])
def courses():
    courses = Course.query.join(Teacher).with_entities(Course.course_code, Course.name,
                                                       Teacher.name.label('teacher_name')).all()
    return render_template("courses.html", courses=courses)


@bp_main.route('/delete_cookie')
def delete_cookie():
    response = make_response(redirect(url_for('main.index')))
    response.set_cookie('name', '', expires=datetime.now())
    return response

comp0034_flask_login_complete/app/templates/_formhelpers.html
{% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
        {% if field.errors %}
            <ul class="alert-warning list-unstyled">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </dd>
{% endmacro %}

comp0034_flask_login_complete/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
<nav class="navbar navbar-expand bg-primary navbar-dark">
    <a class="navbar-brand" href="#">CS Courses</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.courses') }}">Courses</a>
        </li>
        {% if current_user.is_anonymous %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
        {% endif %}
    </ul>
    <form class="form-inline ml-auto" action="search" method="post">
        <input class="form-control" type="search" placeholder="Enter student name" aria-label="Search" name="search_term">
        <button class="btn btn-primary btn-outline-light" type="submit">Search</button>
    </form>
</nav>
<br>
<div role=main class="container">
    {# Displays flashed messages on a page #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert-warning list-unstyled">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block content %}
    {# Child pages add page specific content here #}
    {% endblock %}
</div>
</body>
</html>

comp0034_flask_login_complete/app/templates/base_errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
</body>
</html>

comp0034_flask_login_complete/app/templates/courses.html
{% extends "base.html" %}
{% block title %}Courses{% endblock %}
{% block content %}
{% if courses|length %}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Code</th>
        <th scope="col">Course Name</th>
        <th scope="col">Teacher</th>
    </tr>
    </thead>
    <tbody>
    {% for course in courses %}
    <tr>
        <td>{{ course.course_code }}</td>
        <td>{{ course.name }}</td>
        <td>{{ course.teacher_name }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Sorry, no courses are available at this time</p>
{% endif %}
{% endblock %}

comp0034_flask_login_complete/app/templates/index.html
{# Inherit a parent template called base.html #}
{% extends "base.html" %}
{# Add the title for this page #}
{% block title %}Home{% endblock %}
{# Add the content for this page #}
{% block content %}
    <h1>Welcome {{ name }}</h1>
{% endblock %}

comp0034_flask_login_complete/app/templates/login.html
{% extends 'base.html' %}
{% from "_formhelpers.html" import render_field %}
{% block title %}Login{% endblock %}
{% block content %}
<form method="post" novalidate>
    {{ form.hidden_tag() }}
    <dl>
        {{ render_field(form.email, class='form-control') }}
        {{ render_field(form.password, class='form-control') }}
        {{ render_field(form.remember_me) }}
        <input type=submit value='Login' class='btn btn-primary'>
    </dl>
</form>
{% endblock %}

comp0034_flask_login_complete/app/templates/search_results.html
{% extends "base.html" %}
{% block title %}Search results{% endblock %}
{% block content %}
{% if results|length %}
{# Variable is not empty #}
<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Student name</th>
        <th scope="col">Email</th>
    </tr>
    </thead>
    <tbody> {% for result in results %}
    <tr>
        <td>{{ result.name }}</td>
        <td>{{ result.email }}</td>
    </tr>
     {% endfor %}
    </tbody>
</table>
{% else %}
{# Variable is empty #}
<p>Sorry, no students found</p>
{% endif %}
{% endblock %}

comp0034_flask_login_complete/app/templates/signup.html
{% extends "base.html" %}
{% block title %} Signup {% endblock %}
{% block content %}
    {% from "_formhelpers.html" import render_field %}
    <form method=post novalidate>
        {{ form.csrf_token }}
        <dl>
            {{ render_field(form.title, class='form-control') }}
            {{ render_field(form.name, class='form-control') }}
            {{ render_field(form.role, class='form-control') }}
            {{ render_field(form.uni_id, class='form-control') }}
            {{ render_field(form.email, class='form-control') }}
            {{ render_field(form.password, class='form-control') }}
            {{ render_field(form.confirm, class='form-control') }}
        </dl>
        <br>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
{% endblock %}